"""sync missing tables and columns

Revision ID: ca6ce230ce75
Revises: 001
Create Date: 2026-02-02 07:39:28.870146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca6ce230ce75'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUM types first (they don't exist from first migration)
    applicationstatus_enum = postgresql.ENUM('pending', 'processing', 'matched', 'rejected', name='applicationstatus', create_type=True)
    applicationstatus_enum.create(op.get_bind(), checkfirst=True)
    
    pipelinestatus_enum = postgresql.ENUM('not_started', 'in_progress', 'completed', 'failed', name='pipelinestatus', create_type=True)
    pipelinestatus_enum.create(op.get_bind(), checkfirst=True)
    
    agentrunstatus_enum = postgresql.ENUM('pending', 'running', 'completed', 'failed', name='agentrunstatus', create_type=True)
    agentrunstatus_enum.create(op.get_bind(), checkfirst=True)
    
    reviewseverity_enum = postgresql.ENUM('low', 'medium', 'high', 'critical', name='reviewseverity', create_type=True)
    reviewseverity_enum.create(op.get_bind(), checkfirst=True)
    
    reviewstatus_enum = postgresql.ENUM('pending', 'in_review', 'resolved', 'dismissed', name='reviewstatus', create_type=True)
    reviewstatus_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='agentrunstatus', create_type=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    # Drop foreign key constraint before dropping companies table
    op.drop_constraint('jobs_company_id_fkey', 'jobs', type_='foreignkey')
    op.drop_index('ix_companies_email', table_name='companies')
    op.drop_index('ix_companies_id', table_name='companies')
    op.drop_table('companies')
    op.add_column('applications', sa.Column('linkedin_text', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('pipeline_status', sa.Enum('not_started', 'in_progress', 'completed', 'failed', name='pipelinestatus', create_type=True), nullable=False, server_default='not_started'))
    op.add_column('applications', sa.Column('pipeline_error', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('credential_id', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('applications', 'resume_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'processing', 'matched', 'rejected', name='applicationstatus', create_type=True),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::applicationstatus"))
    op.alter_column('applications', 'test_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_applications_candidate_id', table_name='applications')
    op.drop_index('ix_applications_job_id', table_name='applications')
    op.drop_constraint('applications_candidate_id_fkey', 'applications', type_='foreignkey')
    op.drop_constraint('applications_job_id_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'credentials', ['credential_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'applications', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('candidates', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('candidates', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('candidates_anon_id_key', 'candidates', type_='unique')
    op.drop_index('ix_candidates_anon_id', table_name='candidates')
    op.create_index(op.f('ix_candidates_anon_id'), 'candidates', ['anon_id'], unique=True)
    op.drop_index('ix_candidates_email', table_name='candidates')
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.add_column('credentials', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('credentials', 'hash_sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('credentials', 'signature_b64',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('credentials', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('credentials', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_credentials_application_id', table_name='credentials')
    op.drop_index('ix_credentials_candidate_id', table_name='credentials')
    op.drop_constraint('credentials_candidate_id_fkey', 'credentials', type_='foreignkey')
    op.drop_constraint('credentials_application_id_fkey', 'credentials', type_='foreignkey')
    op.create_foreign_key(None, 'credentials', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'credentials', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.add_column('jobs', sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('jobs', 'company_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('jobs', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('jobs', 'application_deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # Foreign key already dropped above
    op.alter_column('review_cases', 'triggered_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('review_cases', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('low', 'medium', 'high', 'critical', name='reviewseverity', create_type=True),
               existing_nullable=False)
    op.alter_column('review_cases', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('review_cases', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'in_review', 'resolved', 'dismissed', name='reviewstatus', create_type=True),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::reviewstatus"))
    op.alter_column('review_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_review_cases_application_id', table_name='review_cases')
    op.drop_constraint('review_cases_application_id_fkey', 'review_cases', type_='foreignkey')
    op.drop_constraint('review_cases_candidate_id_fkey', 'review_cases', type_='foreignkey')
    op.drop_constraint('review_cases_job_id_fkey', 'review_cases', type_='foreignkey')
    op.create_foreign_key(None, 'review_cases', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review_cases', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review_cases', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop ENUM types at the end
    op.execute('DROP TYPE IF EXISTS reviewstatus')
    op.execute('DROP TYPE IF EXISTS reviewseverity')
    op.execute('DROP TYPE IF EXISTS agentrunstatus')
    op.execute('DROP TYPE IF EXISTS pipelinestatus')
    op.execute('DROP TYPE IF EXISTS applicationstatus')
    
    op.drop_constraint(None, 'review_cases', type_='foreignkey')
    op.drop_constraint(None, 'review_cases', type_='foreignkey')
    op.drop_constraint(None, 'review_cases', type_='foreignkey')
    op.create_foreign_key('review_cases_job_id_fkey', 'review_cases', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key('review_cases_candidate_id_fkey', 'review_cases', 'candidates', ['candidate_id'], ['id'])
    op.create_foreign_key('review_cases_application_id_fkey', 'review_cases', 'applications', ['application_id'], ['id'])
    op.create_index('ix_review_cases_application_id', 'review_cases', ['application_id'], unique=False)
    op.alter_column('review_cases', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('review_cases', 'status',
               existing_type=sa.Enum('pending', 'in_review', 'resolved', 'dismissed', name='reviewstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('review_cases', 'reason',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('review_cases', 'severity',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', name='reviewseverity'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('review_cases', 'triggered_by',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.create_foreign_key('jobs_company_id_fkey', 'jobs', 'companies', ['company_id'], ['id'])
    op.alter_column('jobs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'application_deadline',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('jobs', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('jobs', 'company_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('jobs', 'required_skills')
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.create_foreign_key('credentials_application_id_fkey', 'credentials', 'applications', ['application_id'], ['id'])
    op.create_foreign_key('credentials_candidate_id_fkey', 'credentials', 'candidates', ['candidate_id'], ['id'])
    op.create_index('ix_credentials_candidate_id', 'credentials', ['candidate_id'], unique=False)
    op.create_index('ix_credentials_application_id', 'credentials', ['application_id'], unique=False)
    op.alter_column('credentials', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('credentials', 'issued_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credentials', 'signature_b64',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('credentials', 'hash_sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('credentials', 'created_at')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.create_index('ix_candidates_email', 'candidates', ['email'], unique=False)
    op.drop_index(op.f('ix_candidates_anon_id'), table_name='candidates')
    op.create_index('ix_candidates_anon_id', 'candidates', ['anon_id'], unique=False)
    op.create_unique_constraint('candidates_anon_id_key', 'candidates', ['anon_id'])
    op.alter_column('candidates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('candidates', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_job_id_fkey', 'applications', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key('applications_candidate_id_fkey', 'applications', 'candidates', ['candidate_id'], ['id'])
    op.create_index('ix_applications_job_id', 'applications', ['job_id'], unique=False)
    op.create_index('ix_applications_candidate_id', 'applications', ['candidate_id'], unique=False)
    op.alter_column('applications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'test_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('pending', 'processing', 'matched', 'rejected', name='applicationstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('applications', 'resume_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('applications', 'updated_at')
    op.drop_column('applications', 'credential_id')
    op.drop_column('applications', 'pipeline_error')
    op.drop_column('applications', 'pipeline_status')
    op.drop_column('applications', 'linkedin_text')
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='companies_pkey'),
    sa.UniqueConstraint('email', name='companies_email_key')
    )
    op.create_index('ix_companies_id', 'companies', ['id'], unique=False)
    op.create_index('ix_companies_email', 'companies', ['email'], unique=False)
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###